using System;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Azure.Messaging.EventGrid;
using JosephGuadagno.Broadcasting.Domain.Enums;
using JosephGuadagno.Broadcasting.Domain.Interfaces;
using JosephGuadagno.Broadcasting.Domain.Models;
using JosephGuadagno.Broadcasting.Domain.Models.Events;
using Microsoft.Extensions.Logging.Abstractions;
using Moq;

namespace JosephGuadagno.Broadcasting.Functions.Tests.Twitter;

public class ProcessScheduledItemFiredTests
{
    private static EventGridEvent BuildEventGridEvent(int scheduledItemId)
    {
        var payload = JsonSerializer.Serialize(new ScheduledItemFiredEvent { Id = scheduledItemId });
        return new EventGridEvent("subject", "eventType", "1.0", BinaryData.FromString(payload));
    }

    private static Domain.Models.ScheduledItem BuildScheduledItem(
        int id = 1,
        int primaryKey = 42,
        ScheduledItemType itemType = ScheduledItemType.SyndicationFeedSources) => new()
    {
        Id = id,
        ItemType = itemType,
        ItemPrimaryKey = primaryKey,
        Message = "existing scheduled message",
        SendOnDateTime = DateTimeOffset.UtcNow
    };

    private static Functions.Twitter.ProcessScheduledItemFired BuildSut(
        Mock<IScheduledItemManager> scheduledItemManager,
        Mock<ITwitterManager> twitterManager)
    {
        return new Functions.Twitter.ProcessScheduledItemFired(
            scheduledItemManager.Object,
            twitterManager.Object,
            NullLogger<Functions.Twitter.ProcessScheduledItemFired>.Instance);
    }

    [Fact]
    public async Task RunAsync_WhenTemplateFound_UsesRenderedTextNotAutoGenerated()
    {
        var scheduledItem = BuildScheduledItem();
        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);
        var mockTwitterManager = new Mock<ITwitterManager>();
        mockTwitterManager
            .Setup(m => m.ComposeMessageAsync(It.IsAny<ScheduledItem>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync("Test Blog Post Title - https://example.com/post");
        var sut = BuildSut(mockScheduledItemManager, mockTwitterManager);
        var result = await sut.RunAsync(BuildEventGridEvent(1));
        Assert.NotNull(result);
        Assert.Equal("Test Blog Post Title - https://example.com/post", result!.Text);
    }

    [Fact]
    public async Task RunAsync_WhenTemplateIsNull_FallsBackToAutoGeneratedMessage()
    {
        var scheduledItem = BuildScheduledItem();
        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);
        var mockTwitterManager = new Mock<ITwitterManager>();
        mockTwitterManager
            .Setup(m => m.ComposeMessageAsync(It.IsAny<ScheduledItem>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync("Blog Post: Test Blog Post Title https://example.com/post");
        var sut = BuildSut(mockScheduledItemManager, mockTwitterManager);
        var result = await sut.RunAsync(BuildEventGridEvent(1));
        Assert.NotNull(result);
        Assert.Contains("Blog Post:", result!.Text);
        Assert.Contains("Test Blog Post Title", result!.Text);
    }

    [Fact]
    public async Task RunAsync_WhenTemplateRendersImageUrl_ImageUrlAppearsInResult()
    {
        var scheduledItem = BuildScheduledItem();
        scheduledItem.ImageUrl = "https://cdn.example.com/image.jpg";
        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);
        var mockTwitterManager = new Mock<ITwitterManager>();
        mockTwitterManager
            .Setup(m => m.ComposeMessageAsync(It.IsAny<ScheduledItem>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync("Test Blog Post Title https://cdn.example.com/image.jpg");
        var sut = BuildSut(mockScheduledItemManager, mockTwitterManager);
        var result = await sut.RunAsync(BuildEventGridEvent(1));
        Assert.NotNull(result);
        Assert.Contains("https://cdn.example.com/image.jpg", result!.Text);
    }

    [Fact]
    public async Task RunAsync_WhenScheduledItemImageUrlIsNull_ImageUrlIsEmptyInRenderedTemplate()
    {
        var scheduledItem = BuildScheduledItem();
        scheduledItem.ImageUrl = null;
        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);
        var mockTwitterManager = new Mock<ITwitterManager>();
        mockTwitterManager
            .Setup(m => m.ComposeMessageAsync(It.IsAny<ScheduledItem>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync("Test Blog Post Title|");
        var sut = BuildSut(mockScheduledItemManager, mockTwitterManager);
        var result = await sut.RunAsync(BuildEventGridEvent(1));
        Assert.NotNull(result);
        Assert.Equal("Test Blog Post Title|", result!.Text);
    }

    [Fact]
    public async Task RunAsync_WhenTemplateIsEmptyString_FallsBackToAutoGeneratedMessage()
    {
        var scheduledItem = BuildScheduledItem();
        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);
        var mockTwitterManager = new Mock<ITwitterManager>();
        mockTwitterManager
            .Setup(m => m.ComposeMessageAsync(It.IsAny<ScheduledItem>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync("Blog Post: Test Blog Post Title");
        var sut = BuildSut(mockScheduledItemManager, mockTwitterManager);
        var result = await sut.RunAsync(BuildEventGridEvent(1));
        Assert.NotNull(result);
        Assert.Contains("Blog Post:", result!.Text);
    }

    [Fact]
    public async Task RunAsync_ShouldRequestNewSpeakingEngagementTemplate_WhenItemTypeIsEngagements()
    {
        var scheduledItem = BuildScheduledItem(itemType: ScheduledItemType.Engagements);
        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);
        var mockTwitterManager = new Mock<ITwitterManager>();
        mockTwitterManager
            .Setup(m => m.ComposeMessageAsync(It.IsAny<ScheduledItem>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync("I'm speaking at Tech Conference 2026");
        var sut = BuildSut(mockScheduledItemManager, mockTwitterManager);
        await sut.RunAsync(BuildEventGridEvent(1));
        mockTwitterManager.Verify(m => m.ComposeMessageAsync(scheduledItem, It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task RunAsync_WhenEngagementTemplateFound_RendersEngagementNameAndUrl()
    {
        var scheduledItem = BuildScheduledItem(itemType: ScheduledItemType.Engagements);
        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);
        var mockTwitterManager = new Mock<ITwitterManager>();
        mockTwitterManager
            .Setup(m => m.ComposeMessageAsync(It.IsAny<ScheduledItem>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync("Speaking at Tech Conference 2026 - https://conf.example.com");
        var sut = BuildSut(mockScheduledItemManager, mockTwitterManager);
        var result = await sut.RunAsync(BuildEventGridEvent(1));
        Assert.NotNull(result);
        Assert.Equal("Speaking at Tech Conference 2026 - https://conf.example.com", result!.Text);
    }

    [Fact]
    public async Task RunAsync_WhenEngagementTemplateIsNull_FallsBackToEngagementPost()
    {
        var scheduledItem = BuildScheduledItem(itemType: ScheduledItemType.Engagements);
        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);
        var mockTwitterManager = new Mock<ITwitterManager>();
        mockTwitterManager
            .Setup(m => m.ComposeMessageAsync(It.IsAny<ScheduledItem>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync("I'm speaking at Tech Conference 2026");
        var sut = BuildSut(mockScheduledItemManager, mockTwitterManager);
        var result = await sut.RunAsync(BuildEventGridEvent(1));
        Assert.NotNull(result);
        Assert.Contains("I'm speaking at", result!.Text);
        Assert.Contains("Tech Conference 2026", result!.Text);
    }

    [Fact]
    public async Task RunAsync_ShouldRequestScheduledItemTemplate_WhenItemTypeIsTalks()
    {
        var scheduledItem = BuildScheduledItem(itemType: ScheduledItemType.Talks);
        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);
        var mockTwitterManager = new Mock<ITwitterManager>();
        mockTwitterManager
            .Setup(m => m.ComposeMessageAsync(It.IsAny<ScheduledItem>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync("My talk: Building .NET Apps");
        var sut = BuildSut(mockScheduledItemManager, mockTwitterManager);
        await sut.RunAsync(BuildEventGridEvent(1));
        mockTwitterManager.Verify(m => m.ComposeMessageAsync(scheduledItem, It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task RunAsync_WhenTalkTemplateFound_RendersTalkNameAndUrl()
    {
        var scheduledItem = BuildScheduledItem(itemType: ScheduledItemType.Talks);
        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);
        var mockTwitterManager = new Mock<ITwitterManager>();
        mockTwitterManager
            .Setup(m => m.ComposeMessageAsync(It.IsAny<ScheduledItem>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync("My talk: Building .NET Apps - https://josephguadagno.net/talks/dotnet");
        var sut = BuildSut(mockScheduledItemManager, mockTwitterManager);
        var result = await sut.RunAsync(BuildEventGridEvent(1));
        Assert.NotNull(result);
        Assert.Equal("My talk: Building .NET Apps - https://josephguadagno.net/talks/dotnet", result!.Text);
    }

    [Fact]
    public async Task RunAsync_WhenTalkTemplateIsNull_FallsBackToTalkPost()
    {
        var scheduledItem = BuildScheduledItem(itemType: ScheduledItemType.Talks);
        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);
        var mockTwitterManager = new Mock<ITwitterManager>();
        mockTwitterManager
            .Setup(m => m.ComposeMessageAsync(It.IsAny<ScheduledItem>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync("My talk: Building .NET Apps https://josephguadagno.net/talks/dotnet");
        var sut = BuildSut(mockScheduledItemManager, mockTwitterManager);
        var result = await sut.RunAsync(BuildEventGridEvent(1));
        Assert.NotNull(result);
        Assert.Contains("My talk:", result!.Text);
        Assert.Contains("Building .NET Apps", result!.Text);
    }

    [Fact]
    public async Task RunAsync_ShouldRequestNewYouTubeItemTemplate_WhenItemTypeIsYouTubeSources()
    {
        var scheduledItem = BuildScheduledItem(itemType: ScheduledItemType.YouTubeSources);
        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);
        var mockTwitterManager = new Mock<ITwitterManager>();
        mockTwitterManager
            .Setup(m => m.ComposeMessageAsync(It.IsAny<ScheduledItem>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync("New video: Building Better Apps with .NET");
        var sut = BuildSut(mockScheduledItemManager, mockTwitterManager);
        await sut.RunAsync(BuildEventGridEvent(1));
        mockTwitterManager.Verify(m => m.ComposeMessageAsync(scheduledItem, It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task RunAsync_WhenYouTubeTemplateFound_RendersVideoTitleAndUrl()
    {
        var scheduledItem = BuildScheduledItem(itemType: ScheduledItemType.YouTubeSources);
        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);
        var mockTwitterManager = new Mock<ITwitterManager>();
        mockTwitterManager
            .Setup(m => m.ComposeMessageAsync(It.IsAny<ScheduledItem>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync("New video: Building Better Apps with .NET - https://youtube.com/watch?v=abc123def");
        var sut = BuildSut(mockScheduledItemManager, mockTwitterManager);
        var result = await sut.RunAsync(BuildEventGridEvent(1));
        Assert.NotNull(result);
        Assert.Equal("New video: Building Better Apps with .NET - https://youtube.com/watch?v=abc123def", result!.Text);
    }

    [Fact]
    public async Task RunAsync_WhenYouTubeTemplateIsNull_FallsBackToVideoPost()
    {
        var scheduledItem = BuildScheduledItem(itemType: ScheduledItemType.YouTubeSources);
        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);
        var mockTwitterManager = new Mock<ITwitterManager>();
        mockTwitterManager
            .Setup(m => m.ComposeMessageAsync(It.IsAny<ScheduledItem>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync("New video: Building Better Apps with .NET https://youtube.com/watch?v=abc123def");
        var sut = BuildSut(mockScheduledItemManager, mockTwitterManager);
        var result = await sut.RunAsync(BuildEventGridEvent(1));
        Assert.NotNull(result);
        Assert.Contains("Building Better Apps with .NET", result!.Text);
    }
}
