using System;
using System.Text.Json;
using System.Threading.Tasks;
using Azure.Messaging.EventGrid;
using JosephGuadagno.Broadcasting.Domain.Enums;
using JosephGuadagno.Broadcasting.Domain.Interfaces;
using JosephGuadagno.Broadcasting.Domain.Models;
using JosephGuadagno.Broadcasting.Domain.Models.Events;
using Microsoft.Extensions.Logging.Abstractions;
using Moq;

namespace JosephGuadagno.Broadcasting.Functions.Tests.Bluesky;

public class ProcessScheduledItemFiredTests
{
    private static EventGridEvent BuildEventGridEvent(int scheduledItemId)
    {
        var payload = JsonSerializer.Serialize(new ScheduledItemFiredEvent { Id = scheduledItemId });
        return new EventGridEvent("subject", "eventType", "1.0", BinaryData.FromString(payload));
    }

    private static Domain.Models.ScheduledItem BuildScheduledItem(int id = 1, int primaryKey = 42) => new()
    {
        Id = id,
        ItemType = ScheduledItemType.SyndicationFeedSources,
        ItemPrimaryKey = primaryKey,
        Message = "existing scheduled message",
        SendOnDateTime = DateTimeOffset.UtcNow
    };

    private static SyndicationFeedSource BuildFeedSource() => new()
    {
        Id = 42,
        FeedIdentifier = "feed-1",
        Title = "Test Blog Post Title",
        Url = "https://example.com/post",
        ShortenedUrl = null,
        Author = "Author",
        PublicationDate = DateTimeOffset.UtcNow,
        AddedOn = DateTimeOffset.UtcNow,
        LastUpdatedOn = DateTimeOffset.UtcNow
    };

    private static Functions.Bluesky.ProcessScheduledItemFired BuildSut(
        Mock<IScheduledItemManager> scheduledItemManager,
        Mock<ISyndicationFeedSourceManager> feedSourceManager,
        Mock<IYouTubeSourceManager> youTubeSourceManager,
        Mock<IEngagementManager> engagementManager,
        Mock<IMessageTemplateDataStore> messageTemplateDataStore)
    {
        return new Functions.Bluesky.ProcessScheduledItemFired(
            scheduledItemManager.Object,
            feedSourceManager.Object,
            youTubeSourceManager.Object,
            engagementManager.Object,
            messageTemplateDataStore.Object,
            NullLogger<Functions.Bluesky.ProcessScheduledItemFired>.Instance);
    }

    [Fact]
    public async Task RunAsync_WhenTemplateFound_UsesRenderedTextNotAutoGenerated()
    {
        // Arrange
        var scheduledItem = BuildScheduledItem();
        var feedSource = BuildFeedSource();
        var messageTemplate = new MessageTemplate
        {
            Platform = "Bluesky",
            MessageType = "RandomPost",
            Template = "{{ title }} - {{ url }}"
        };

        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);

        var mockFeedSourceManager = new Mock<ISyndicationFeedSourceManager>();
        mockFeedSourceManager.Setup(m => m.GetAsync(42)).ReturnsAsync(feedSource);

        var mockMessageTemplateDataStore = new Mock<IMessageTemplateDataStore>();
        mockMessageTemplateDataStore.Setup(m => m.GetAsync("Bluesky", "RandomPost")).ReturnsAsync(messageTemplate);

        var sut = BuildSut(
            mockScheduledItemManager,
            mockFeedSourceManager,
            new Mock<IYouTubeSourceManager>(),
            new Mock<IEngagementManager>(),
            mockMessageTemplateDataStore);

        // Act
        var result = await sut.RunAsync(BuildEventGridEvent(1));

        // Assert — rendered text, not the "Blog Post: ..." fallback
        Assert.Equal("Test Blog Post Title - https://example.com/post", result);
    }

    [Fact]
    public async Task RunAsync_WhenTemplateIsNull_FallsBackToAutoGeneratedMessage()
    {
        // Arrange
        var scheduledItem = BuildScheduledItem();
        var feedSource = BuildFeedSource();

        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);

        var mockFeedSourceManager = new Mock<ISyndicationFeedSourceManager>();
        mockFeedSourceManager.Setup(m => m.GetAsync(42)).ReturnsAsync(feedSource);

        var mockMessageTemplateDataStore = new Mock<IMessageTemplateDataStore>();
        mockMessageTemplateDataStore.Setup(m => m.GetAsync("Bluesky", "RandomPost")).ReturnsAsync((MessageTemplate?)null);

        var sut = BuildSut(
            mockScheduledItemManager,
            mockFeedSourceManager,
            new Mock<IYouTubeSourceManager>(),
            new Mock<IEngagementManager>(),
            mockMessageTemplateDataStore);

        // Act
        var result = await sut.RunAsync(BuildEventGridEvent(1));

        // Assert — fallback generates "Blog Post: ..." format
        Assert.NotNull(result);
        Assert.Contains("Blog Post:", result);
        Assert.Contains("Test Blog Post Title", result);
    }

    [Fact]
    public async Task RunAsync_WhenTemplateRendersImageUrl_ImageUrlAppearsInResult()
    {
        // Arrange
        var scheduledItem = BuildScheduledItem();
        scheduledItem.ImageUrl = "https://cdn.example.com/image.jpg";

        var feedSource = BuildFeedSource();
        var messageTemplate = new MessageTemplate
        {
            Platform = "Bluesky",
            MessageType = "RandomPost",
            Template = "{{ title }} {{ image_url }}"
        };

        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);

        var mockFeedSourceManager = new Mock<ISyndicationFeedSourceManager>();
        mockFeedSourceManager.Setup(m => m.GetAsync(42)).ReturnsAsync(feedSource);

        var mockMessageTemplateDataStore = new Mock<IMessageTemplateDataStore>();
        mockMessageTemplateDataStore.Setup(m => m.GetAsync("Bluesky", "RandomPost")).ReturnsAsync(messageTemplate);

        var sut = BuildSut(
            mockScheduledItemManager,
            mockFeedSourceManager,
            new Mock<IYouTubeSourceManager>(),
            new Mock<IEngagementManager>(),
            mockMessageTemplateDataStore);

        // Act
        var result = await sut.RunAsync(BuildEventGridEvent(1));

        // Assert
        Assert.NotNull(result);
        Assert.Contains("https://cdn.example.com/image.jpg", result);
    }

    [Fact]
    public async Task RunAsync_WhenScheduledItemImageUrlIsNull_ImageUrlIsEmptyInRenderedTemplate()
    {
        // Arrange
        var scheduledItem = BuildScheduledItem();
        scheduledItem.ImageUrl = null;

        var feedSource = BuildFeedSource();
        var messageTemplate = new MessageTemplate
        {
            Platform = "Bluesky",
            MessageType = "RandomPost",
            Template = "{{ title }}|{{ image_url }}"
        };

        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);

        var mockFeedSourceManager = new Mock<ISyndicationFeedSourceManager>();
        mockFeedSourceManager.Setup(m => m.GetAsync(42)).ReturnsAsync(feedSource);

        var mockMessageTemplateDataStore = new Mock<IMessageTemplateDataStore>();
        mockMessageTemplateDataStore.Setup(m => m.GetAsync("Bluesky", "RandomPost")).ReturnsAsync(messageTemplate);

        var sut = BuildSut(
            mockScheduledItemManager,
            mockFeedSourceManager,
            new Mock<IYouTubeSourceManager>(),
            new Mock<IEngagementManager>(),
            mockMessageTemplateDataStore);

        // Act
        var result = await sut.RunAsync(BuildEventGridEvent(1));

        // Assert — image_url renders as empty string
        Assert.NotNull(result);
        Assert.Equal("Test Blog Post Title|", result);
    }

    [Fact]
    public async Task RunAsync_WhenTemplateIsEmptyString_FallsBackToAutoGeneratedMessage()
    {
        // Arrange
        var scheduledItem = BuildScheduledItem();
        var feedSource = BuildFeedSource();
        var messageTemplate = new MessageTemplate
        {
            Platform = "Bluesky",
            MessageType = "RandomPost",
            Template = ""   // empty → TryRenderTemplateAsync returns null → fallback
        };

        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);

        var mockFeedSourceManager = new Mock<ISyndicationFeedSourceManager>();
        mockFeedSourceManager.Setup(m => m.GetAsync(42)).ReturnsAsync(feedSource);

        var mockMessageTemplateDataStore = new Mock<IMessageTemplateDataStore>();
        mockMessageTemplateDataStore.Setup(m => m.GetAsync("Bluesky", "RandomPost")).ReturnsAsync(messageTemplate);

        var sut = BuildSut(
            mockScheduledItemManager,
            mockFeedSourceManager,
            new Mock<IYouTubeSourceManager>(),
            new Mock<IEngagementManager>(),
            mockMessageTemplateDataStore);

        // Act
        var result = await sut.RunAsync(BuildEventGridEvent(1));

        // Assert — empty template is treated as no template → fallback
        Assert.NotNull(result);
        Assert.Contains("Blog Post:", result);
    }
}
