using System;
using System.Text.Json;
using System.Threading.Tasks;
using Azure.Messaging.EventGrid;
using JosephGuadagno.Broadcasting.Domain.Constants;
using JosephGuadagno.Broadcasting.Domain.Enums;
using JosephGuadagno.Broadcasting.Domain.Interfaces;
using JosephGuadagno.Broadcasting.Domain.Models;
using JosephGuadagno.Broadcasting.Domain.Models.Events;
using Microsoft.Extensions.Logging.Abstractions;
using Moq;

namespace JosephGuadagno.Broadcasting.Functions.Tests.Facebook;

public class ProcessScheduledItemFiredTests
{
    private static EventGridEvent BuildEventGridEvent(int scheduledItemId)
    {
        var payload = JsonSerializer.Serialize(new ScheduledItemFiredEvent { Id = scheduledItemId });
        return new EventGridEvent("subject", "eventType", "1.0", BinaryData.FromString(payload));
    }

    private static Domain.Models.ScheduledItem BuildScheduledItem(int id = 1, int primaryKey = 42) => new()
    {
        Id = id,
        ItemType = ScheduledItemType.SyndicationFeedSources,
        ItemPrimaryKey = primaryKey,
        Message = "existing scheduled message",
        SendOnDateTime = DateTimeOffset.UtcNow
    };

    private static SyndicationFeedSource BuildFeedSource() => new()
    {
        Id = 42,
        FeedIdentifier = "feed-1",
        Title = "Test Blog Post Title",
        Url = "https://example.com/post",
        ShortenedUrl = null,
        Author = "Author",
        PublicationDate = DateTimeOffset.UtcNow,
        AddedOn = DateTimeOffset.UtcNow,
        LastUpdatedOn = DateTimeOffset.UtcNow
    };

    private static Functions.Facebook.ProcessScheduledItemFired BuildSut(
        Mock<IScheduledItemManager> scheduledItemManager,
        Mock<ISyndicationFeedSourceManager> feedSourceManager,
        Mock<IYouTubeSourceManager> youTubeSourceManager,
        Mock<IEngagementManager> engagementManager,
        Mock<IMessageTemplateDataStore> messageTemplateDataStore)
    {
        return new Functions.Facebook.ProcessScheduledItemFired(
            scheduledItemManager.Object,
            engagementManager.Object,
            feedSourceManager.Object,
            youTubeSourceManager.Object,
            messageTemplateDataStore.Object,
            NullLogger<Functions.Facebook.ProcessScheduledItemFired>.Instance);
    }

    [Fact]
    public async Task RunAsync_WhenTemplateFound_OverridesStatusTextWithRenderedText()
    {
        // Arrange
        var scheduledItem = BuildScheduledItem();
        var feedSource = BuildFeedSource();
        var messageTemplate = new MessageTemplate
        {
            Platform = "Facebook",
            MessageType = "NewSyndicationFeedItem",
            Template = "{{ title }} - {{ url }}"
        };

        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);

        var mockFeedSourceManager = new Mock<ISyndicationFeedSourceManager>();
        mockFeedSourceManager.Setup(m => m.GetAsync(42)).ReturnsAsync(feedSource);

        var mockMessageTemplateDataStore = new Mock<IMessageTemplateDataStore>();
        mockMessageTemplateDataStore.Setup(m => m.GetAsync(MessageTemplates.Platforms.Facebook, MessageTemplates.MessageTypes.NewSyndicationFeedItem)).ReturnsAsync(messageTemplate);

        var sut = BuildSut(
            mockScheduledItemManager,
            mockFeedSourceManager,
            new Mock<IYouTubeSourceManager>(),
            new Mock<IEngagementManager>(),
            mockMessageTemplateDataStore);

        // Act
        var result = await sut.RunAsync(BuildEventGridEvent(1));

        // Assert — StatusText overridden by Scriban render; LinkUri still from the item
        Assert.NotNull(result);
        Assert.Equal("Test Blog Post Title - https://example.com/post", result.StatusText);
        Assert.Equal("https://example.com/post", result.LinkUri);
    }

    [Fact]
    public async Task RunAsync_WhenTemplateIsNull_StatusTextUsesAutoGeneratedFallback()
    {
        // Arrange
        var scheduledItem = BuildScheduledItem();
        var feedSource = BuildFeedSource();

        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);

        var mockFeedSourceManager = new Mock<ISyndicationFeedSourceManager>();
        mockFeedSourceManager.Setup(m => m.GetAsync(42)).ReturnsAsync(feedSource);

        var mockMessageTemplateDataStore = new Mock<IMessageTemplateDataStore>();
        mockMessageTemplateDataStore.Setup(m => m.GetAsync(MessageTemplates.Platforms.Facebook, MessageTemplates.MessageTypes.NewSyndicationFeedItem)).ReturnsAsync((MessageTemplate?)null);

        var sut = BuildSut(
            mockScheduledItemManager,
            mockFeedSourceManager,
            new Mock<IYouTubeSourceManager>(),
            new Mock<IEngagementManager>(),
            mockMessageTemplateDataStore);

        // Act
        var result = await sut.RunAsync(BuildEventGridEvent(1));

        // Assert — StatusText is the auto-generated "ICYMI: Blog Post: ..." fallback
        Assert.NotNull(result);
        Assert.Contains("ICYMI:", result.StatusText);
        Assert.Contains("Test Blog Post Title", result.StatusText);
        Assert.Equal("https://example.com/post", result.LinkUri);
    }

    [Fact]
    public async Task RunAsync_WhenTemplateRendersImageUrl_ImageUrlAppearsInStatusText()
    {
        // Arrange
        var scheduledItem = BuildScheduledItem();
        scheduledItem.ImageUrl = "https://cdn.example.com/image.jpg";

        var feedSource = BuildFeedSource();
        var messageTemplate = new MessageTemplate
        {
            Platform = "Facebook",
            MessageType = "NewSyndicationFeedItem",
            Template = "{{ title }} {{ image_url }}"
        };

        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);

        var mockFeedSourceManager = new Mock<ISyndicationFeedSourceManager>();
        mockFeedSourceManager.Setup(m => m.GetAsync(42)).ReturnsAsync(feedSource);

        var mockMessageTemplateDataStore = new Mock<IMessageTemplateDataStore>();
        mockMessageTemplateDataStore.Setup(m => m.GetAsync(MessageTemplates.Platforms.Facebook, MessageTemplates.MessageTypes.NewSyndicationFeedItem)).ReturnsAsync(messageTemplate);

        var sut = BuildSut(
            mockScheduledItemManager,
            mockFeedSourceManager,
            new Mock<IYouTubeSourceManager>(),
            new Mock<IEngagementManager>(),
            mockMessageTemplateDataStore);

        // Act
        var result = await sut.RunAsync(BuildEventGridEvent(1));

        // Assert
        Assert.NotNull(result);
        Assert.Contains("https://cdn.example.com/image.jpg", result.StatusText);
    }

    [Fact]
    public async Task RunAsync_WhenScheduledItemImageUrlIsNull_ImageUrlIsEmptyInRenderedStatusText()
    {
        // Arrange
        var scheduledItem = BuildScheduledItem();
        scheduledItem.ImageUrl = null;

        var feedSource = BuildFeedSource();
        var messageTemplate = new MessageTemplate
        {
            Platform = "Facebook",
            MessageType = "NewSyndicationFeedItem",
            Template = "{{ title }}|{{ image_url }}"
        };

        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);

        var mockFeedSourceManager = new Mock<ISyndicationFeedSourceManager>();
        mockFeedSourceManager.Setup(m => m.GetAsync(42)).ReturnsAsync(feedSource);

        var mockMessageTemplateDataStore = new Mock<IMessageTemplateDataStore>();
        mockMessageTemplateDataStore.Setup(m => m.GetAsync(MessageTemplates.Platforms.Facebook, MessageTemplates.MessageTypes.NewSyndicationFeedItem)).ReturnsAsync(messageTemplate);

        var sut = BuildSut(
            mockScheduledItemManager,
            mockFeedSourceManager,
            new Mock<IYouTubeSourceManager>(),
            new Mock<IEngagementManager>(),
            mockMessageTemplateDataStore);

        // Act
        var result = await sut.RunAsync(BuildEventGridEvent(1));

        // Assert — image_url renders as empty string
        Assert.NotNull(result);
        Assert.Equal("Test Blog Post Title|", result.StatusText);
    }

    [Fact]
    public async Task RunAsync_LinkUri_IsAlwaysFromItemRegardlessOfTemplate()
    {
        // Arrange — template does NOT mention url, but LinkUri must still be the item's URL
        var scheduledItem = BuildScheduledItem();
        var feedSource = BuildFeedSource();
        var messageTemplate = new MessageTemplate
        {
            Platform = "Facebook",
            MessageType = "NewSyndicationFeedItem",
            Template = "Just the title: {{ title }}"
        };

        var mockScheduledItemManager = new Mock<IScheduledItemManager>();
        mockScheduledItemManager.Setup(m => m.GetAsync(1)).ReturnsAsync(scheduledItem);

        var mockFeedSourceManager = new Mock<ISyndicationFeedSourceManager>();
        mockFeedSourceManager.Setup(m => m.GetAsync(42)).ReturnsAsync(feedSource);

        var mockMessageTemplateDataStore = new Mock<IMessageTemplateDataStore>();
        mockMessageTemplateDataStore.Setup(m => m.GetAsync(MessageTemplates.Platforms.Facebook, MessageTemplates.MessageTypes.NewSyndicationFeedItem)).ReturnsAsync(messageTemplate);

        var sut = BuildSut(
            mockScheduledItemManager,
            mockFeedSourceManager,
            new Mock<IYouTubeSourceManager>(),
            new Mock<IEngagementManager>(),
            mockMessageTemplateDataStore);

        // Act
        var result = await sut.RunAsync(BuildEventGridEvent(1));

        // Assert — LinkUri is always the item URL, never affected by template
        Assert.NotNull(result);
        Assert.Equal("https://example.com/post", result.LinkUri);
        Assert.Equal("Just the title: Test Blog Post Title", result.StatusText);
    }
}
