// <auto-generated> This file has been auto generated for RBAC Phase 1. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JosephGuadagno.Broadcasting.Data.Sql.Models;

public partial class ApplicationUser
{
    public int Id { get; set; }

    public string EntraObjectId { get; set; }

    public string DisplayName { get; set; }

    public string Email { get; set; }

    public string ApprovalStatus { get; set; }

    public string ApprovalNotes { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset UpdatedAt { get; set; }

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();

    public virtual ICollection<UserApprovalLog> UserApprovalLogs { get; set; } = new List<UserApprovalLog>();

    public virtual ICollection<UserApprovalLog> AdminUserApprovalLogs { get; set; } = new List<UserApprovalLog>();
}
