// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace JosephGuadagno.Broadcasting.Data.Sql.Models;

public partial class EmailTemplate
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public DateTimeOffset CreatedDate { get; set; }

    public DateTimeOffset UpdatedDate { get; set; }
}
