// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JosephGuadagno.Broadcasting.Data.Sql.Models;

public partial class Engagement
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Url { get; set; }

    public DateTimeOffset StartDateTime { get; set; }

    public DateTimeOffset EndDateTime { get; set; }

    public string Comments { get; set; }

    public string TimeZoneId { get; set; }

    public DateTimeOffset CreatedOn { get; set; }

    public DateTimeOffset LastUpdatedOn { get; set; }

    public string? CreatedByEntraOid { get; set; }

    public virtual ICollection<Talk> Talks { get; set; } = new List<Talk>();

    public virtual ICollection<EngagementSocialMediaPlatform> SocialMediaPlatforms { get; set; } = new List<EngagementSocialMediaPlatform>();
}