// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JosephGuadagno.Broadcasting.Data.Sql.Models;

public partial class EngagementSocialMediaPlatform
{
    public int EngagementId { get; set; }

    public int SocialMediaPlatformId { get; set; }

    public string Handle { get; set; }

    public virtual Engagement Engagement { get; set; }

    public virtual SocialMediaPlatform SocialMediaPlatform { get; set; }
}
