// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JosephGuadagno.Broadcasting.Data.Sql.Models;

public partial class FeedCheck
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTimeOffset LastCheckedFeed { get; set; }

    public DateTimeOffset LastItemAddedOrUpdated { get; set; }

    public DateTimeOffset LastUpdatedOn { get; set; }
}