// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JosephGuadagno.Broadcasting.Data.Sql.Models;

public partial class MessageTemplate
{
    public int SocialMediaPlatformId { get; set; }

    public string MessageType { get; set; }

    public string Template { get; set; }

    public string Description { get; set; }

    public string? CreatedByEntraOid { get; set; }

    public virtual SocialMediaPlatform SocialMediaPlatform { get; set; }
}