// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace JosephGuadagno.Broadcasting.Data.Sql.Models;

public partial class MessageTemplate
{
    public int SocialMediaPlatformId { get; set; }

    public string MessageType { get; set; } = null!;

    public string Template { get; set; } = null!;

    public string? Description { get; set; }

    /// <summary>The Entra OID of the owner. Empty string is the system-default sentinel.</summary>
    public string CreatedByEntraOid { get; set; } = string.Empty;

    public virtual SocialMediaPlatform? SocialMediaPlatform { get; set; }
}