// <auto-generated> This file has been auto generated for RBAC Phase 1. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JosephGuadagno.Broadcasting.Data.Sql.Models;

public partial class Role
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}
