// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JosephGuadagno.Broadcasting.Data.Sql.Models;

public partial class ScheduledItem
{
    public int Id { get; set; }

    public string ItemTableName { get; set; }

    public int ItemPrimaryKey { get; set; }

    public string Message { get; set; }

    public DateTimeOffset SendOnDateTime { get; set; }

    public bool MessageSent { get; set; }

    public DateTimeOffset? MessageSentOn { get; set; }

    public string ImageUrl { get; set; }

    public string? CreatedByEntraOid { get; set; }
}