// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JosephGuadagno.Broadcasting.Data.Sql.Models;

public partial class SocialMediaPlatform
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Url { get; set; }

    public string Icon { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<EngagementSocialMediaPlatform> EngagementSocialMediaPlatforms { get; set; } = new List<EngagementSocialMediaPlatform>();

    public virtual ICollection<UserPublisherSetting> UserPublisherSettings { get; set; } = new List<UserPublisherSetting>();
}
