// <auto-generated> This file has been auto generated for RBAC Phase 1. </auto-generated>
#nullable disable
using System;

namespace JosephGuadagno.Broadcasting.Data.Sql.Models;

public partial class UserApprovalLog
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int? AdminUserId { get; set; }

    public string Action { get; set; }

    public string Notes { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public virtual ApplicationUser User { get; set; }

    public virtual ApplicationUser AdminUser { get; set; }
}
