// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace JosephGuadagno.Broadcasting.Data.Sql.Models;

public partial class UserPublisherSetting
{
    public int Id { get; set; }

    public string CreatedByEntraOid { get; set; }

    public int SocialMediaPlatformId { get; set; }

    public bool IsEnabled { get; set; }

    public string Settings { get; set; }

    public DateTimeOffset CreatedOn { get; set; }

    public DateTimeOffset LastUpdatedOn { get; set; }

    public virtual SocialMediaPlatform SocialMediaPlatform { get; set; }
}
