// <auto-generated> This file has been auto generated for RBAC Phase 1. </auto-generated>
#nullable disable
using System;

namespace JosephGuadagno.Broadcasting.Data.Sql.Models;

public partial class UserRole
{
    public int UserId { get; set; }

    public int RoleId { get; set; }

    public virtual ApplicationUser User { get; set; }

    public virtual Role Role { get; set; }
}
