### Documentation for the Facebook Graph API Tokens
## https://developers.facebook.com/docs/pages/access-tokens/

### Get a short-lived access token
## Documentation https://developers.facebook.com/docs/graph-api/guides/explorer#get-token-dropdown
## Get the short lived access token from the Graph API Explorer: https://developers.facebook.com/tools/explorer/

### Get the long-lived access token
# Need to look at the "expires_in": 5184000 for the number of seconds until this expires
GET https://graph.facebook.com/{{graph-api-version}}/oauth/access_token?grant_type=fb_exchange_token&
    client_id={{app-id}}&
    client_secret={{app-secret}}&
    fb_exchange_token={{short-lived-access-token}}

<> 2023-08-06T102330.200.json
<> 2023-08-06T102309.400.js
<> 2023-08-06T094625.400.js

### Refresh an expired long-lived access token
# Need to look at the "expires_in": 5184000 for the number of seconds until this expires
GET https://graph.facebook.com/{{graph-api-version}}/oauth/access_token?grant_type=fb_exchange_token&
    client_id={{app-id}}&
    client_secret={{app-secret}}&
    set_token_expires_in_60_days=true&
    fb_exchange_token={{long-lived-access-token}}

### Refresh an expired page access token
# Need to look at the "expires_in": 5184000 for the number of seconds until this expires
GET https://graph.facebook.com/{{graph-api-version}}/oauth/access_token?grant_type=fb_exchange_token&
    client_id={{app-id}}&
    client_secret={{app-secret}}&
    set_token_expires_in_60_days=true&
    fb_exchange_token={{page-access-token}}


### Get a Long-Lived Page Access Token
## Documentation https://developers.facebook.com/docs/facebook-login/guides/access-tokens/get-long-lived#long-lived-page-token
# Need to look at the "expires_in": 5184000 for the number of seconds until this expires
GET https://graph.facebook.com/{{graph-api-version}}/{{user-id}}/accounts?access_token={{long-lived-access-token}}

### Get the pages for a user
## Documentation: https://developers.facebook.com/docs/pages-api/manage-pages#get-your-pages
GET https://graph.facebook.com/{{graph-api-version}}/{{user-id}}/accounts?access_token={{long-lived-access-token}}

### Get the page access token
### Take the long-lived access token and get the page access token
GET https://graph.facebook.com/{{graph-api-version}}/{{page-id}}?fields=access_token&access_token={{page-access-token}}

<> 2023-08-06T102534.200.js

### Get page insights: JosephGuadagno.NET
GET https://graph.facebook.com/{{graph-api-version}}/{{page-id}}/insights/page_impressions_unique?access_token={{page-access-token}}

### Get details of page: JosephGuadagno.NET
GET https://graph.facebook.com/{{graph-api-version}}/{{page-id}}/?fields=about,attire,bio,location,parking,hours,emails,website&access_token={{page-access-token}}

<> 2023-08-06T102607.200.js
<> 2023-08-05T163533.400.js
<> 2023-08-05T163400.400.js
<> 2023-08-05T163242.400.js
<> 2023-08-05T163044.400.js
<> 2023-08-05T163013.400.js
<> 2023-08-05T162639.400.js

### Sample page post
POST https://graph.facebook.com/{{page-id}}/feed
    ?message=Test Page Post&link=https://josephguadagno.net/&access_token={{page-access-token}}