### Collectors - Syndication Feed

# @name Run Collectors_Feed Load All Posts
POST http://{{host}}/api/CollectorsFeedLoadAllPosts?CheckFrom=2026-01-01

###
# @name Run Collectors_Feed Load All Posts - No Date
POST http://{{host}}/api/CollectorsFeedLoadAllPosts

###
# @name Run Collectors_SpeakingEngagements Load All Videos
POST http://{{host}}/api/CollectorsSpeakingEngagementsLoadAll?CheckFrom=2026-02-02

###
# @name Run Collectors_SpeakingEngagements Load All Videos - No Date
POST http://{{host}}/api/CollectorsSpeakingEngagementsLoadAll

###
# @name Run Collectors_YouTube Load All Videos
POST http://{{host}}/api/CollectorsYouTubeLoadAllVideos?CheckFrom=2025-06-12

###
# @name Run Collectors_YouTube Load All Videos - No Date
POST http://{{host}}/api/CollectorsYouTubeLoadAllVideos

###
POST https://jjgnet-broadcast.azurewebsites.net/admin/functions/FacebookTokenRefresh
x-functions-key: {{functions-key}}
Content-Type: application/json

{}
