### Run Collectors_Feed Load All Posts

POST http://localhost:7071/api/CollectorsFeedLoadAllPosts?CheckFrom=2025-02-05

### Run Collectors_Feed Load All Posts - No Date

POST http://localhost:7071/api/CollectorsFeedLoadAllPosts

### Run Collectors_YouTube Load All Videos

POST http://localhost:7071/api/CollectorsYouTubeLoadAllVideos?CheckFrom=2025-02-05

### Run Collectors_YouTube Load All Videos - No Date

POST http://localhost:7071/api/CollectorsYouTubeLoadAllVideos

###
POST https://jjgnet-broadcast.azurewebsites.net/api/CollectorsFeedLoadAllPosts

###
POST https://jjgnet-broadcast.azurewebsites.net/api/CollectorsYouTubeLoadAllVideos

###
POST https://jjgnet-broadcast.azurewebsites.net/admin/functions/facebook_refresh_tokens
x-functions-key: {{functions-key}}
Content-Type: application/json

{}